core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/urls.py
#
from django.urls import path
from employee.views import EmployeeView,HomeView, SalaryView, LoginView
app_name = 'employee'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('salary/', SalaryView.as_view(), name='salary'),
    path('employee/', EmployeeView.as_view(), name='employee'),
    path('login/', LoginView.as_view(), name='login')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

    {% load static %}
    <link rel="stylesheet" href="{% static 'fonts/themify-icons/themify-icons.css' %}">
    {%block stylesheets%} {%endblock stylesheets%}

    <title>{%block title%} {%endblock%}</title>
</head>


<body>
    <main class="main">
        <div class="wrapped">
            {%include 'nav-bar.html'%}
            {%block content%}
            {%endblock content%}
        </div>

    </main>
    {% block javascripts %}{% endblock javascripts %}
</body>

templates/error.html
<div class="noise"></div>
<div class="overlay"></div>
<div class="terminal">
  <h1>Error <span class="errorcode">Face not found</span></h1>
  <p class="output">Không thể tìm thấy bất kì một khuôn mặt nào trong ảnh</p>
  <p class="output">Please try to <a href="{%url 'employee:employee'%}">go back</a>
</div>

<script src="'https://fonts.googleapis.com/css?family=Inconsolata'"></script>

<style>
html {
  min-height: 100%;
}

body {
  box-sizing: border-box;
  height: 100%;
  background-color: #000000;
  background-image: radial-gradient(#11581E, #041607), url("https://media.giphy.com/media/oEI9uBYSzLpBK/giphy.gif");
  background-repeat: no-repeat;
  background-size: cover;
  font-family: 'Inconsolata', Helvetica, sans-serif;
  font-size: 1.5rem;
  color: rgba(128, 255, 128, 0.8);
  text-shadow:
      0 0 1ex rgba(51, 255, 51, 1),
      0 0 2px rgba(255, 255, 255, 0.8);
}

.noise {
  pointer-events: none;
  position: absolute;
  width: 100%;
  height: 100%;
  background-image: url("https://media.giphy.com/media/oEI9uBYSzLpBK/giphy.gif");
  background-repeat: no-repeat;
  background-size: cover;
  z-index: -1;
  opacity: .02;
}

.overlay {
  pointer-events: none;
  position: absolute;
  width: 100%;
  height: 100%;
  background:
      repeating-linear-gradient(
      180deg,
      rgba(0, 0, 0, 0) 0,
      rgba(0, 0, 0, 0.3) 50%,
      rgba(0, 0, 0, 0) 100%);
  background-size: auto 4px;
  z-index: 1;
}

.overlay::before {
  content: "";
  pointer-events: none;
  position: absolute;
  display: block;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
  background-image: linear-gradient(
      0deg,
      transparent 0%,
      rgba(32, 128, 32, 0.2) 2%,
      rgba(32, 128, 32, 0.8) 3%,
      rgba(32, 128, 32, 0.2) 3%,
      transparent 100%);
  background-repeat: no-repeat;
  animation: scan 7.5s linear 0s infinite;
}

@keyframes scan {
  0%        { background-position: 0 -100vh; }
  35%, 100% { background-position: 0 100vh; }
}

.terminal {
  box-sizing: inherit;
  position: absolute;
  height: 100%;
  width: 1000px;
  max-width: 100%;
  padding: 4rem;
  text-transform: uppercase;
}

.output {
  color: rgba(128, 255, 128, 0.8);
  text-shadow:
      0 0 1px rgba(51, 255, 51, 0.4),
      0 0 2px rgba(255, 255, 255, 0.8);
}

.output::before {
  content: "> ";
}

/*
.input {
  color: rgba(192, 255, 192, 0.8);
  text-shadow:
      0 0 1px rgba(51, 255, 51, 0.4),
      0 0 2px rgba(255, 255, 255, 0.8);
}

.input::before {
  content: "$ ";
}
*/

a {
  color: #fff;
  text-decoration: none;
}

a::before {
  content: "[";
}

a::after {
  content: "]";
}

.errorcode {
  color: white;
}
</style>

templates/nav-bar.html
<!-- menu start -->
<div class="col-menu col-6">
    <div class="navigation">
        <div class="menuToggle">
            <i class="ti-menu menuToggle-icon"></i>
        </div>
        <ul class="menuList">
            <li class="menuList-item {%ifequal name "home"%}active{%endifequal%}">
                <a href="{%url 'employee:home'%}">
                    <div class="menulist-item-icon">
                        <i class="ti-home"></i>
                    </div>
                    <span class="menuList-item-text">Trang chủ</span>
                </a>
            </li>
            <li class="menuList-item {%ifequal name "employee"%}active{%endifequal%}">
                <a href="{% url 'employee:employee' %}">
                    <div class="menulist-item-icon">
                        <i class="ti-user"></i>
                    </div>
                    <span class="menuList-item-text">Nhân viên</span>
                </a>
            </li>
            <li class="menuList-item {%ifequal name "salary"%}active{%endifequal%}">
                <a href="{% url 'employee:salary'%}">
                    <div class="menulist-item-icon">
                        <i class="ti-bar-chart"></i>
                    </div>
                    <span class="menuList-item-text">Tính lương</span>
                </a>
            </li>
        </ul>
        <!-- account login start -->
        <!-- <div class="account-login">
            <div class="user-admin">
                <div class="user-admin-img"></div>
                <span class="user-admin-name">Nguyễn Duy Hiếu</span>
            </div>
            <button class="logout-btn">Logout</button>
        </div> -->
        <!-- account login end -->
    </div>
</div>
<!-- menu end -->